# Generated by Django 2.2 on 2019-04-30 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('document', models.FileField(upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=30)),
                ('question', models.CharField(max_length=2048)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('requester', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=256)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('test_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('sequence', models.SmallIntegerField()),
                ('page', models.SmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Student')),
            ],
        ),
    ]
