# Generated by Django 2.2 on 2019-04-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('designer', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=2048)),
                ('label', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('requester', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Layout')),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Survey'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Layout')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Student')),
            ],
        ),
    ]
