# Generated by Django 2.2 on 2019-05-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='label',
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='sequence',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Survey'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
