# Generated by Django 2.2 on 2019-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190425_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='layout',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='survey',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
