# Generated by Django 2.2 on 2019-04-26 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190426_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='layout',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='survey',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
