# Generated by Django 2.2.1 on 2019-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20190502_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
    ]
