# Generated by Django 2.2 on 2019-04-26 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20190426_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
