# Generated by Django 2.2 on 2019-04-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_survey_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='format',
        ),
    ]
