# Generated by Django 2.2.1 on 2019-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_question_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('section', models.CharField(blank=True, max_length=256)),
                ('instructor', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
